name: CD
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org/'

    - run: ./bin/setup
    - run: ./bin/build
    - run: ./bin/publish

    - name: Record Linear release
      uses: linear/linear-release-action@v0
      with:
        name: ${{ github.event.release.tag_name }}
        version: ${{ github.event.release.tag_name }}
        access_key: ${{ secrets.LINEAR_ACCESS_KEY }}
