name: CI
on:
  push:
    branches:
      - '*'
env:
  HOME: /root # https://github.com/microsoft/playwright/issues/6500
jobs:
  CI:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.40.0-jammy

    steps:
    - uses: actions/checkout@v3
    - run: chmod -R a+rw test
    - uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        registry-url: https://registry.npmjs.org/
        cache: "npm"

    - run: ./bin/setup
    - run: ./bin/test_units
    - run: ./bin/test_screenshots --native --shard 1/3
    - run: ./bin/test_screenshots --native --shard 2/3
    - run: ./bin/test_screenshots --native --shard 3/3
    - run: ./bin/test_accessibility --native
    - run: ./bin/lint
    - run: ./bin/build

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Screenshot Comparison Results
        path: test/results
        retention-days: 7
