name: CI
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.28.1-focal

    steps:
    - uses: actions/checkout@v3
    - run: chmod -R a+rw test
    - uses: actions/setup-node@v3
      with:
        cache: "npm"

    - run: ./bin/setup
    - run: ./bin/test_units
    - run: ./bin/test_features --native
    - run: ./bin/lint
    - run: ./bin/build

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Screenshot Comparison Results
        path: test/results
        retention-days: 7

